# Generated by Django 3.0.8 on 2021-01-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210101_2031'),
        ('kit', '0002_auto_20201227_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated', models.IntegerField(verbose_name='Number of this product buyed')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kit.Kit', verbose_name='Kit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Product')),
            ],
        ),
    ]
