# Generated by Django 3.0.8 on 2021-01-06 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0003_kit_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name of the project')),
                ('bio', models.CharField(max_length=200, verbose_name='Project Bio')),
            ],
        ),
        migrations.RemoveField(
            model_name='kit_info',
            name='project_name',
        ),
        migrations.AddField(
            model_name='kit_info',
            name='img',
            field=models.ImageField(default='/files/images/defaultImage.jpg', upload_to='files/images/'),
        ),
        migrations.AlterField(
            model_name='kit_product',
            name='donated',
            field=models.IntegerField(verbose_name='Number of this product donated'),
        ),
        migrations.AlterField(
            model_name='kit_product',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kit.Kit', verbose_name='Kit'),
        ),
        migrations.AddField(
            model_name='kit_info',
            name='project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='kit.Project', verbose_name='Name of the project'),
        ),
    ]
