# Generated by Django 3.0.8 on 2021-01-13 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0012_auto_20210113_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kit',
            old_name='kit_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='kit',
            name='description',
            field=models.CharField(default='Historia e decricao do kit', max_length=200, verbose_name='Kit name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kit_product',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kit.Kit', verbose_name='Kit'),
        ),
    ]
