# Generated by Django 3.1.6 on 2021-02-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0014_auto_20210113_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit_product',
            name='in_kit',
            field=models.IntegerField(default=0, verbose_name='Number of this product in a kit'),
        ),
    ]
