# Generated by Django 3.1.6 on 2021-02-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0015_kit_product_in_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='imgUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='img',
            field=models.ImageField(blank=True, default='defaultImage.jpg', null=True, upload_to=''),
        ),
    ]
