# Generated by Django 3.0.8 on 2020-12-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Product Name')),
                ('quotation_date', models.DateField(verbose_name='Quotation Date')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Quotation Date')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Product Name')),
                ('description', models.CharField(max_length=140, verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('in_kit', models.IntegerField(verbose_name='Number of this product in a kit')),
            ],
        ),
    ]
