# Generated by Django 3.0.8 on 2021-01-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_outfitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitter',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Outfitter Name'),
        ),
        migrations.AlterField(
            model_name='outfitter',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website link'),
        ),
    ]
