# Generated by Django 3.0.8 on 2021-01-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210101_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='defaultImage.jpg', upload_to=''),
        ),
    ]
