# Generated by Django 3.1.6 on 2021-02-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_kit',
        ),
        migrations.AddField(
            model_name='product',
            name='imgUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='defaultImage.jpg', null=True, upload_to=''),
        ),
    ]
